image: python:2.7

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - ~/.cache/pip/

stages:
  - test
  - doc
  - deploy

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  - python -V
  - pip install -r requirements.txt

test:
  stage: test
  allow_failure: false
  script:
    - git --no-pager diff --check `git log --oneline | tail -1 | cut --fields=1 --delimiter=' '`
    - flake8
    - py.test -vv --cov-config .coveragerc --cov geolink_formatter geolink_formatter/tests

sphinx:
  stage: doc
  script:
    - sphinx-versioning build doc/source doc/build/html
  artifacts:
    paths:
      - doc/build/html
    expire_in: 1 day
  only:
    - master

pages:
  stage: deploy
  dependencies:
    - sphinx
  script:
    - mv doc/build/html/ public/
  artifacts:
    paths:
      - public
    expire_in: 1 day
  only:
    - master
