sudo: required

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

stages:
  - test
  - deploy

install:
  - python -V
  - pip install -r requirements.txt

script:
  - git --no-pager diff --check `git log --oneline | tail -1 | cut --fields=1 --delimiter=' '`
  - flake8
  - py.test -vv --cov-config .coveragerc --cov geolink_formatter tests

pages:
  stage: deploy
  install:
    - pip install -r requirements.txt
  script:
    - sphinx-versioning build doc/source docs
#  only:
#    - tags
#    - master

after_success:
  - bash <(curl -s https://codecov.io/bash)
