sudo: required

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

stages:
  - test
  - deploy

install:
  - python -V
  - pip install -r requirements.txt

script:
  - git --no-pager diff --check `git log --oneline | tail -1 | cut --fields=1 --delimiter=' '`
  - flake8
  - py.test -vv --cov-config .coveragerc --cov geolink_formatter tests

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - python -V
  - pip install -r requirements.txt

jobs:
  include:
    - provider: script
      stage: deploy
      python: '3.6'
      script: sphinx-versioning push doc/source/ gh-pages .
      skip_cleanup: true
      on:
#        branch: master
        repo: openoereb/geolink_formatter
    - provider: script
      stage: deploy
      python: '3.6'
      script: sphinx-versioning push doc/source/ gh-pages .
      skip_cleanup: true
      on:
        tags: true
        repo: openoereb/geolink_formatter
    - provider: pypi
      stage: deploy
      python: '3.6'
      server: https://upload.pypi.org/legacy/
      user: kdeininger
      password:
        secure: "DRam+gSbTi1t6oDxtEA1C6Cm1vN4dJ3uKOlepBGYmnIsx8ckjjHsza5zaRPBFuw54VjxmdT2IQ+dUD6d0PgZwRNHV/YuC73tA3n6QRPmmU4h3hDq4+ZiNMpw75Vog9kmhJOGRVZRvV/kqbpCg+4aJfPuDaFRqfjBDYY32nKBCHioxsTtZd4DXius4iBlwh0stWEYx4EMIGrGX1S0IppdIYuFdCEAK90UqASJ0cLXQd4A72j74KSAvLdY1Az1N0ciKqg4n307vwK9xg/o8xqGQtbl2PRtZ2tLM+TPLQ3RAsLtPImUHDrBOSC1U/pb8pqXZhwLjjW9uMzCBwH6asMpThJGempub2wSyc6KyT8b0p1zKYpGc9Jzghndeobv5JlmeGs56adm8thxxOM4jCdbGeLWMf/tVATxdl572nS6Tvn72aMsx0M7rLmXUDTH2rgOjf0/oJYVjAxnpGYRzfgfU7AakIpoVA1+NCp1xTEdZbOKxY4gyqoUQ/NZyyQBd6a3zoEET1isQarDAVhMIiGz7Py4iejIqsFthyKfvBikRJeZA/LhMu4p57Q6gIDndGuuX+IyJyi3yEmeBS2froqOfAjZFlqcHz2JkdJ2LATiTfZt0bWrx2Se1aiVdbHkZ75Qk546KMdKbwfjwMhX21GRjWTycsF91SBf19SDdgFrKpI="
      distributions: sdist bdist_wheel
      skip_upload_docs: true
      skip_cleanup: true
      on:
        tags: true
        repo: openoereb/geolink_formatter
    - provider: pypi
      stage: deploy
      python: '3.6'
      server: https://test.pypi.org/legacy/
      user: kdeininger
      password:
        secure: "D5gVZYSdVYYCf0ZtbvmZHXOcdGsJog6kqm51whMyVrle/MGKFCNR/Vfo4kB6UDTItcgLZhYhUEFCxIi1E94eTgunEPj5/0ZkcLI+hO270CGTE6OaLUriyEcWVoQ9MCqZcdUV0QhsgoDRsZ/44IEDORB33hi432GmghAH1lQQ1ouZ8ZSGBivN+bGJoC7UOjXu/zzQXgjYpUlTzGDTUhuZjo4KamKxHGC5llPcnr38ZWrBwPiUZY8W7fxlOo+Ek8wlVbNQmyfuwOE3kUwAb/6QyQS3rKz+Aa7Yd5qgp1V9/9QaijwOkO8hsCeyoazJ1l4AQwuygGMVhT52Te/xM6FmSaAa2w+XFVa43gyEkbb51JCsk/eaarXBN/gHKUb7/zsOgL974fAZHu748lIlNaNrkb2COJ8DN+c7PF7RRljclWhyq3CI9+8ynz3QLCAL49pvRSySMU7ixoqVxRUtqipbF50R+KipbuT+J0q3LR0Jbc0/eaVKJ14zU80CQORy9LCw3291zhr+SmOKQH+E+RqQvYtt0eFaQC/B+bEeGWZYcS+sXodZ306pMyZPaAFMayEDT9yGhLiZNXT6lpFEgjDNaBXEj6Rzui5KfgecpPR00ACTntTdCwFqSXum7qZdGDjUMvKTSdD5i5AlBjzh76KQhCC8N72M/sxnhogayu1taHs="
      distributions: sdist bdist_wheel
      skip_upload_docs: true
      skip_cleanup: true
      on:
#        branch: master
        repo: openoereb/geolink_formatter
